# Generated by Django 5.2 on 2025-05-08 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
